### ISSUE TITLE
character 

### ISSUE THREAD

**Issue by SilgerZuo** [Jamling/SmartQQ4IntelliJ#1]
os:ubuntu 17.04
idea:17.02
language:chinese
![screenshot from 2017-07-16 21-34-29](https://user-images.githubusercontent.com/15605139/28248034-01a28d84-6a6f-11e7-96ef-f8a490a473de.png)

**Comment by Jamling** [comment]
你那三个`口`是输入的？输入的中文变成了乱码吗？

**Comment by SilgerZuo** [comment]
不好意思一直没看到。昨天更新了，你已经修好了，棒棒哒！

**Comment by Jamling** [comment]
Greate! Ubuntu好像不能使用PC QQ，我虽然是Windows系统，但是公司限制使用PC QQ，同勉~
