### ISSUE TITLE
官网插件一直没更新，本地从git上导出的代码如何安装呢

### ISSUE THREAD

**Issue by biwin-wangli** [Jamling/SmartQQ4IntelliJ#14]

**Comment by Jamling** [comment]
Git导出的只是源代码哦，你可以对源代码编译打包生成可运行的插件包。本地安装，请参考[Release](https://github.com/Jamling/SmartQQ4IntelliJ/releases/) [v2.0.1](https://github.com/Jamling/SmartQQ4IntelliJ/releases/tag/v2.0.1)。下载本地插件后，再在IntelliJ中安装。
