### ISSUE TITLE
哥、这是我见过最屌的项目

### ISSUE THREAD

**Issue by eaglewu** [Jamling/SmartQQ4IntelliJ#21]
给你一万个 👍

**Comment by Jamling** [comment]
谢谢了~ 其实web qq和微信网页版早就有了。不过大多用来做机器人。

**Comment by kumfo** [comment]
最喜欢你这种奇思淫巧的。

**Comment by Jamling** [comment]
@kumfo 哈哈，要是老板允许我们用PC QQ，我也懒得花时间，毕竟IntelliJ的插件开发，我是一窍不通。

**Comment by canaan-yz** [comment]
赞。一直在找win下命令行的微信工具，发现要么机器人要么linux下要么封装的api要自己开发要么ide插件开发会的人少。楼主开发的插件使用简单，功能正常。

**Comment by Jamling** [comment]
@canaan-yz 如果使用命令行，python版的weixin-bot应该是最好的选择。

**Comment by SbyXlmm** [comment]
@Jamling 真有创意

**Comment by IceMimosa** [comment]
吊到不行。

**Comment by clouduan** [comment]
Google "jetbrains plugin" 看到被摆在首页上，实在是亮眼睛，可以说很秀了。

**Comment by Jamling** [comment]
@clouduan 略显尴尬的是google在中国大陆通过正常的方式访问不了
