### ISSUE TITLE
插件bug

### ISSUE THREAD

**Issue by adminChina** [Jamling/SmartQQ4IntelliJ#26]
com.scienjus.smartqq.handler.FriendHandler 两处数组越界
反编译代码
1、
categoryMap.put(category.getIndex(), category);
2、
((Category) categoryMap.get(item.get("categories").getAsInt())).addFriend(friend);

两处bug需要添加数组越界判断
1、
int index = category.getIndex();
if (index >= categoryMap.size()) {
   index = 0;
}
categoryMap.put(index, category);

2、
int index = item.get("categories").getAsInt();
if (index >= categoryMap.size()) {
                index = 0;
}
((Category) categoryMap.get(index )).addFriend(friend);

**Comment by Jamling** [comment]
@adminChina 哥们，你竟然反编译了！源代码其实是公开的 😆 ，谢谢建议~

**Comment by Jamling** [comment]
Souce code: 
```java
        Map<Integer, Category> categoryMap = new TreeMap<>();
        JsonArray categories = result.getAsJsonArray("categories");
        
        categoryMap.put(0, Category.defaultCategory());
        
        for (int i = 0; categories != null && i < categories.size(); i++) {
            JsonObject item = categories.get(i).getAsJsonObject();
            Category category = handleCategory(item);
            categoryMap.put(category.getIndex(), category); // IndexOutOfBound?
        }
```
categoryMap是不限定大小的，应该不会IndexOutOfBound，如果你可以重现，请下载[SmartIM](https://github.com/Jamling/SmartIM)代码，在smartqq模块中debug一下。

**Comment by adminChina** [comment]
![g d nftms 8l45c 79 2](https://user-images.githubusercontent.com/17397276/34027505-1c5a71be-e198-11e7-8a79-660114b80e37.png)

2017-12-15 13:00:31.011 [Thread-4] ERROR (LOG.java:37) -
				SmartQQ初始化失败
java.lang.NullPointerException: null
	at com.scienjus.smartqq.handler.FriendHandler.handleCategoryList(FriendHandler.java:95)
	at com.scienjus.smartqq.client.SmartQQClient.init(SmartQQClient.java:216)
	at cn.ieclipse.smartqq.QQContactView.doLoadContacts(QQContactView.java:103)
	at cn.ieclipse.smartim.views.IMContactView$1.run(IMContactView.java:70)

![ax775 yzgaj sb7 c9u c](https://user-images.githubusercontent.com/17397276/34027648-0e02dba0-e199-11e7-82b9-a427c2ba606e.png)


错误我贴出来了，你看吧，这边categoryMap.size = 1 catId = 6 ，所以导致报错

**Comment by Jamling** [comment]
已更新
```java
            int catId = item.get("categories").getAsInt();
            Category category = categoryMap.get(catId);
            // fix https://github.com/Jamling/SmartQQ4IntelliJ/issues/26
            if (category == null) {
                category = Category.unknownCategory(catId);
                categoryMap.put(category.getIndex(), category);
            }
            category.addFriend(friend);
```

**Comment by adminChina** [comment]
我这边安装你的插件，登陆报错，而我同事却是正常使用，我以为是我的分组的问题，删除分组只留下一个（默认分组修改了名称），然后还是报错，后面我就反编译你的代码，发现你这边代码和我的分组对不上，就对你的代码做了修改 ，然后提出bug。

**Comment by Jamling** [comment]
@adminChina 那估计是腾讯后台缓存未同步更新导致的。smart qq腾讯也不维护，存在比较多的bug。你登录报错应该不是这个原因引起的。可能是别的原因。
