### ISSUE TITLE
wechat timeline error

### ISSUE THREAD

**Issue by zzfeng** [Jamling/SmartQQ4IntelliJ#30]
微信聊天时，自己发出去的消息显示当前时间是正常的。但是对方回复的时候显示的时间有误，不是当前时间。如下图:  1是我发的消息，时间正常。2是对方回复的消息，时间有误。
![issue](https://user-images.githubusercontent.com/14360729/33984054-432d6cee-e0f1-11e7-826a-740020ec925d.png)

**Comment by Jamling** [comment]
transfer to https://github.com/Jamling/SmartIM/issues/2
Fixed
