### ISSUE TITLE
QR Code invalid when QQ login

### ISSUE THREAD

**Issue by changxinjie** [Jamling/SmartQQ4IntelliJ#42]
![image](https://user-images.githubusercontent.com/9565184/38024259-08cab9b8-32b7-11e8-9f14-400a064c20ae.png)

I think it is necessary to add a link to refresh the QR code.

**Comment by Jamling** [comment]
Timeout problem occured a day ago, now fixed by Tencent.

The qrcode expired you can re-login to get new qrcode.
