### ISSUE TITLE
微信好友列表为空

### ISSUE THREAD

**Issue by fuyucn** [Jamling/SmartQQ4IntelliJ#51]
登陆后，微信好友列表只有一个`group`，无其他。public里面也是空的。

**Comment by Jamling** [comment]
先把版本信息，系统信息贴上来

**Comment by fuyucn** [comment]
win10. Intellij Idea 2018.2.4 . SmartQQ v2.4.0

**Comment by Jamling** [comment]
此版本正常，尝试重新登录呢？

**Comment by fuyucn** [comment]
重新登陆后，会显示，切换tab或者其他，然后就又不显示了。

**Comment by Jamling** [comment]
这还是第一次遇到，如果你熟悉java的话，可以运行一下源代码debug一下。
