### ISSUE TITLE
Smartqq登录不上

### ISSUE THREAD

**Issue by androidzhang** [Jamling/SmartQQ4IntelliJ#6]
手机qq扫描二维码怎么登录不上？

**Comment by Jamling** [comment]
有具体的错误提示吗？或者点击x之后重试

**Comment by androidzhang** [comment]
早解決了  退了重试就可以了

**Comment by sunflowerseat** [comment]
登陆上了 发不出消息呢 
11:02:47 发送失败: 内容：嘿(发送失败，Api返回码[100001])
10:55:07 发送失败: 内容：好厉害啊(发送失败，Api返回码[0])

**Comment by Jamling** [comment]
@sunflowerseat 前阵子QQ协议有变更，我还未更新插件，所有的发送消息，发送的所有消息均会提示发送失败，实际上发送应该是成功的。再等几天吧，新版插件正在开发中
