### ISSUE TITLE
SmartQQ消息发送成功但是Event Log提示发送失败

### ISSUE THREAD

**Issue by CNmanyue** [Jamling/SmartQQ4IntelliJ#7]
![1508485954 1](https://user-images.githubusercontent.com/9784893/31810551-c5ed4794-b5ae-11e7-8fa6-95dd9477b324.jpg)
![1508485974 1](https://user-images.githubusercontent.com/9784893/31810552-c6210386-b5ae-11e7-9e9a-76a41eb6a70b.jpg)

**Comment by Jamling** [comment]
因QQ协议变更，原有的解析代码已不适用，会提示发送失败，实际上是发送成功的。此issue会在smartqq 2.x版本中一并修复。
